name: Altguide Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'RoboticsHardwareSolutions/altguide'
          ref: 'main' 
          path: altguide

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd altguide
          python -m pip install --upgrade pip
          pip install -r utils/pcb_checker/requirements.txt

      - name: Run altguide script
        run: |
          cd altguide
          python utils/pcb_checker/main.py "${{ github.workspace }}"
