name: Altguide Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: List directory contents
        run: |
          echo "Содержимое /home/runner/work/BareMetal-PLC-M:"
          ls -la /home/runner/work/BareMetal-PLC-M
          echo "Содержимое /home/runner/work/BareMetal-PLC-M/BareMetal-PLC-M:"
          ls -la ${{ github.workspace }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'RoboticsHardwareSolutions/altguide'
          ref: 'main' 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r utils/pcb_checker/requirements.txt

      - name: Run altguide script
        run: |
          python utils/pcb_checker/main.py "${{ github.workspace }}"
